language: bash
services: docker

env:
  - VERSION=latest
  - VERSION=7.0

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - test latest = "$VERSION" || cd "$VERSION"
  - image="marceloalmeida/php-couchbase-builddeb:${VERSION}"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
